### ISSUE TITLE
file.rra :undefined method  

### ISSUE THREAD

**Issue by hachpai** [t3hk0d3/rrd-ruby#1]
I think it should be file.header.rra

**Comment by t3hk0d3** [comment]
Can you please send backtrace?

**Comment by hachpai** [comment]
Yes,

```
[15] pry(main)> file.rra
NoMethodError: undefined method `rra' for #<RRD::File:0x007fb4428876f8>
```

**Comment by michaelkl** [comment]
Got the same issue.
Even for `file.header.rra` I got:
```
irb(main):014:0> file.header.rra
NoMethodError: undefined method `unpack' for nil:NilClass
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:56:in `read'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:65:in `block in read_uniparams'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:64:in `times'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:64:in `each'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:64:in `map'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/reader.rb:64:in `read_uniparams'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/data_source.rb:17:in `parse'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/header.rb:43:in `block in parse'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/header.rb:42:in `times'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/header.rb:42:in `parse'
	from /var/lib/gems/2.1.0/gems/rrd-ruby-1.0.1/lib/rrd/file.rb:15:in `header'
	from (irb):14
	from /usr/bin/irb:11:in `<main>'
irb(main):015:0> file
=> #<RRD::File:0x1e90600 @reader=#<RRD::Reader:0x1e7e8d0 @file=#<File:/var/spool/th.rrd>, @endianess=:little, @alignment=8, @symbol_cache={"a*"=>"a*", "Q<Q<Q<"=>"Q<Q<Q<", "A*"=>"A*"}>>
```

**Comment by t3hk0d3** [comment]
@michaelkl Can you please upload your RRD file somewhere? Looks like something wrong with header.

Looks like file being exhausted faster than DS unival being readed:  

https://github.com/oetiker/rrdtool-1.x/blob/master/src/rrd_format.h#L173
https://github.com/t3hk0d3/rrd-ruby/blob/master/lib/rrd/data_source.rb#L17

**Comment by michaelkl** [comment]
@t3hk0d3  https://yadi.sk/d/2aKLJ-h23GAZdY

Created with RRDtool 1.4.8. I'm using armv7l kernel. May it be an _little-BIG-endian_ issue?

**Comment by t3hk0d3** [comment]
@michaelkl 
Probably, however there is little-/big endian support, but it were never really tested.
Thank you for file.
